language:
  python

python:
  - 3.6

install:
  - pip install --upgrade -r requirements.dev.txt

script:
  - export
  - pylama bitstore
  - python -m pytest tests -sv --cov=bitstore

after_success:
  - coveralls
